/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Nuit de l'info 2024 - Void LR - API Documentation
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

export const appControllerGetData = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.get(`/api`, options);
};

export const getAppControllerGetDataQueryKey = () => {
  return [`/api`] as const;
};

export const getAppControllerGetDataQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetData>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetData>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetDataQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerGetData>>
  > = ({ signal }) => appControllerGetData({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerGetDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetData>>
>;
export type AppControllerGetDataQueryError = AxiosError<unknown>;

export function useAppControllerGetData<
  TData = Awaited<ReturnType<typeof appControllerGetData>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetData>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerGetDataQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
